// coverage:ignore-file
// libadd - example of native_toolchain_cmake
//    License: Apache-2.0
// Author: Rainyl
// License: Apache-2.0
// Date: 2025/2/14

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:example/example.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int32 Function(ffi.Int32, ffi.Int32)>()
external int math_add(
  int a,
  int b,
);
